title: "KQL Security Training Platform"
description: "Master threat detection with hands-on KQL scenarios"
baseurl: "/KQLified"
url: "https://realnamesareboring.github.io/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Include assets
include:
  - assets